#! /bin/bash

trap 'echo error detected on line $__LINE__: $?; exit 8' ERR

cd /usr/mcsi-linux

find . \( -name .git -prune \) -o -type f -print |
while read name
do
	name=${name#./}
	source="/usr/local/$name"
	target="/usr/mcsi-linux/$name"
	cmp -s $target $source && ln -sf $target $source
done
exit 0

