#! /bin/bash
#
# Relocate /usr/mcsi-linux to /usr/mcsi/linux to make room for other MCSI libraries
#
test=''
[[ $1 = "-t" ]] && test=echo
trap "Unexpected error at line __LINE__" ERR

# Relocate the actual directory.
[[ ! -d /usr/mcsi ]] && mkdir /usr/mcsi && mv /usr/mcsi-linux /usr/mcsi/linux

# Find and fix any symbolic links.
find / \
	\( \
		   -wholename /dev -prune \
		-o -wholename /mnt -prune \
		-o -wholename /net -prune \
		-o -wholename /proc -prune \
		-o -wholename /sys -prune \
		-o -wholename /usr/local/dirvish -prune \
		-o -wholename /usr/local/lxc -prune \
	\) \
	-o -type l -print |
while read line
do  link=`readlink $line`
   [[ "$link" = */mcsi-linux/* ]] || continue
   newlink=`echo $link | sed 's/mcsi-linux/mcsi\/linux/'`
   $test ln -sf $newlink $line
done

# Fix up checkall's .cfg file reference.
[[ -f /usr/local/etc/checkall.cfg ]] && $test sed -i 's/mcsi-linux/mcsi\/linux/' /usr/local/etc/checkall.cfg
