#! /bin/bash

function ReadLSOF {
	grep tree/ |
	head -n 1 | 
	while read trash pid trash fh type trash item7 item8 rest
	do
		if [[ "$type" = "unknown" ]]
		then
			filename="$item7 item8 rest"
		else
			filename="${rest# *}"
			filename="${filename# *}"
		fi
		# [[ $fh = [0-9]*r ]] && continue			# Filter out input file.
		filename="${filename% (*}"			# Clean up NFS mounts.

#		1               2     3    4     5    6
#		Filesystem      Size  Used Avail Use% Mounted on
#		/dev/md2         46G  9.8G   34G  23% /
		space=`df -hlP "${filename%/*}" 2> /dev/null | awk '!/Filesystem/ {print \$4 "/" $5;}'`

		# Get size in a compact unit.
		size=`stat -c %s "$filename" 2> /dev/null`
		if [[ -z "$size" ]]
		then
			size='  ?'
		elif [[ size -gt 1024**4 ]]
		then
			size=`printf "%'dT" $(($size/1024**4))`
		elif [[ size -gt 1024**3 ]]
		then
			size=`printf "%'dG" $(($size/1024**3))`
		elif [[ size -gt 1024**2 ]]
		then
			size=`printf "%'dM" $(($size/1024**2))`
		elif [[ $size -gt 1024 ]]
		then
			size=`printf "%dK" $(($size/1024))`
		else
			size="${size}B"
		fi

		filename=`echo "$filename" | sed 's/^.*\/\(.*\/.*\/tree\)/\1/'`		# Strip down to vault.
		printf "%-s %5d %-6s %8s %4s: %s\n" $now $pid "rsync" $space $size "$filename"
	done 
}

Once=$1
while ps -ef | grep dirvish | grep -qv grep
do
	now=`date +%T`

	# Report on rsync's in progress
	ps -ef |
	grep rsync |
	grep -v grep |
	while read trash pid trash
	do
		lsof -p $pid |
			ReadLSOF
	done |
	sort

	# Report on dirvish-expire in progress
	prior=''
	ps -ef | 
	grep dirvish-expire |
	grep -v grep |
	while read trash pid trash
	do
		line=`pstree -p $pid`
		line=${line##*--rm(}
		line=${line%%)*}
		[[ $line =~ /^[0-9]+$/ ]] || continue
		[[ -n $line ]] && lsof -p $line | 
			grep ' [0-9]r  *DIR '
	done |
	while read trash pid trash trash trash trash trash trash dir
	do
		dir=${dir%%/tree/*}
		percent=`df -hlP "$dir" | awk '!/Filesystem/ {print \$4 "/" \$5}'`
		printf "%-s %5d %-6s %4s: %s\n" $now $pid "expire" $percent "$dir"
	done |
	sort -r |
	while read current
	do
		if [[ -z "$prior" || "$prior" != $current* ]]
		then
			echo "$current"
		fi
		prior=$current
	done
	[[ "$Once" = "1" ]] && exit
	sleep 30
done
date '+No dirvish processes running at %T'

