#!/bin/sh
# Ref www.brandonhutchinson.com/chroot_ssh.html

CHROOT_DIR=$1
if [[ $# -ne 1 ]]
then
	echo "usage: $0 chroot-path" >&2
	exit 8
fi
if [[ "$1" = "/" ]]
then
	echo "/ refused"
	exit 10
fi

REQUIRED_DIRS="		 etc \
			 dev"

REQUIRED_CHROOT_FILES="  /bin/cp \
                         /bin/ls \
                         /bin/mkdir \
                         /bin/mv \
                         /bin/rm \
                         /bin/rmdir \
                         /bin/sh \
                         /usr/bin/ldd \
                         /usr/bin/scp \
                         /usr/bin/groups \
                         /usr/bin/id \
                         /bin/bash \
			 /lib/libnss_compat.so.2 \
                         /usr/lib/ssh/sftp-server"

REQUIRED_EMPTY_FILES="	/etc/security/limits.conf"

# Create $CHROOT_DIR
[ ! -d $CHROOT_DIR ] && mkdir $CHROOT_DIR
cd $CHROOT_DIR
if [[ "$PWD" != "$CHROOT_DIR" ]]
then
	echo "Unable to cd to $CHROOT_DIR.  Landed in $PWD." >2
	exit 9
fi

# Create any essential directories.  Note that directories will
# also be created as necessary for any required files.
for DIR in $REQUIRED_DIRS
do
   if [[ ! -d $DIR ]]
   then
      mkdir -p $DIR || echo "Unable to create $DIR: status $?"
   fi
done

# Copy $REQUIRED_CHROOT_FILES and shared library dependencies
# to chroot environment

for FILE in $REQUIRED_CHROOT_FILES
do
   DIR=`dirname $FILE | cut -c2-`
   [ ! -d $DIR ] && mkdir -p $DIR
   cp $FILE `echo $FILE | cut -c2-`
   [[ -x $FILE ]] && for SHARED_LIBRARY in `ldd $FILE | sed 's/^.*=>//;s/(.*$//;/not a dynamic/d'`
   do
      DIR=`dirname $SHARED_LIBRARY | cut -c2-`
      [ ! -d $DIR ] && mkdir -p $DIR
      [ ! -s "`echo $SHARED_LIBRARY | cut -c2-`" ] && \
      cp $SHARED_LIBRARY `echo $SHARED_LIBRARY | cut -c2-`
   done
done

#cp /usr/lib/ld.so.1 usr/lib

# Create required character devices
for name in "zero" "null"
do
	[[ -e $CHROOT_DIR/dev/$name ]] && rm $CHROOT_DIR/dev/$name
	MajMin=`ls -l /dev/$name | awk '{print $5, $6}' | sed 's/,//g'`
	mknod $CHROOT_DIR/dev/$name c $MajMin || \
		echo "Unable to create $CHROOT_DIR/dev/$name: status $?"
	chmod 666 $CHROOT_DIR/dev/$name || \
		echo "Unable to chmod $CHROOT_DIR/dev/$name: status $?"
done

# Create necessary dummy files.
for FILE in $REQUIRED_EMPTY_FILES
do
   FILE="${CHROOT_DIR}/$FILE"
   DIR=`dirname $FILE`
   [ ! -d $DIR ] && mkdir -p $DIR
   if [[ ! -e $FILE ]]
   then
      touch $FILE || echo "Unable to create $FILE: status $?"
   fi
done

cat <<-ENDNOTES

Remaining manual tasks:
1) For sftp, you'll need to create a $CHROOT_DIR/etc/passwd entry for the user(s).
2) For scp support (at least for winscp), you'll need to create /etc/group
entries for the groups that the user(s) are in.

ENDNOTES

