#! /bin/bash

mysql  <<ENDMYSQL
SELECT table_schema "Data Base Name", sum( data_length + index_length ) / 1024 / 1024 as MB FROM information_schema.TABLES GROUP BY table_schema order by MB desc;
ENDMYSQL
