#! /bin/bash

# Display the network driver for each NIC

for f in /sys/class/net/*
do
      dev=$(basename $f)
      [[ $dev = lo* ]] && continue
      driver=$(readlink $f/device/driver/module)
      if [ $driver ]
      then
            driver=$(basename $driver)
      fi
      addr=$(cat $f/address)
      operstate=$(cat $f/operstate)
      printf "%10s [%s]: %10s (%s)\n" "$dev" "$addr" "$driver" "$operstate"
done
