#!/bin/bash
#
# Document a process' memory consumption in Mb
#
#    Example: processmem-to-mrtg mysqld
#
#    Sample MRTG entry:
#	Target[mongomem]: `/usr/local/sbin/processmem-to-mrtg mongod`
#	Title[mongomem]: Mongo Memory Usage
#	Options[mongomem]: growright,nopercent,gauge
#	MaxBytes[mongomem]: 67108
#	AbsMax[mongomem]: 134217
#	Kilo[mongomem]: 1024
#	kMG[mongomem]: ,,
#	YLegend[mongomem]: Mb
#	ShortLegend[mongomem]: Mb
#	Legend1[mongomem]: Resident
#	Legend2[mongomem]: Virtual
#	LegendI[mongomem]: Resident
#	LegendO[mongomem]: Virtual
#	PageTop[mongomem]: <H1>Mongo Memory Usage</H1><a href="index.shtml">(Return to main page)</a><br>
#	Unscaled[mongomem]: none

function procmem
{
	pid=`pidof $1`
	if [[ $? -eq 0 ]]
	then
		line=`echo $pid | xargs ps -o rss,vsz | sed '/RSS/d;s/^ *//;s/ *$//;'`
		rss=${line%% *}
		vsz=${line##* }
		((rss=($rss+512)/1024))	# Convert to Mb
		((vsz=($vsz+512)/1024))	# Convert to Mb
		echo $rss $vsz
	else
		echo 0 0
	fi
}

line=$(procmem $1)
rss=${line%% *}
vsz=${line##* }
printf "$rss\n$vsz\n0\n0\n"
