#! /bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/root/bin

if [[ $# -eq 0 ]]
then
	echo "usage: $0 name [...]" 1>&2
	exit 4
fi

if [[ `id -un` != root ]]
then
	sudo "$0" "$@"
	((ExitRC-$?))
else
	((ExitRC=0))
	for name in $*
	do
		nameplus="${name}d"
		nameminus=${name%d}
		if [[ -e "/etc/init.d/$name" ]]
		then
			# No change required.
			:
		elif [[ -e "/etc/init.d/$nameminus" ]]
		then
			name=$nameminus
		elif [[ -e "/etc/init.d/$nameplus" ]]
		then
			name=$nameplus
		fi
		echo "Restarting $name..."
		eval /etc/init.d/$name stop
		eval /etc/init.d/$name start
		((Status=$?))
		[[ $Status -gt $ExitRC ]] && ((ExitRC=Status))
	done
fi

exit $ExitRC
