#!/bin/bash

# Found code to check which SSL encryption algorithms
# a port supports.
#
# test-web-encryption servername [port] [filter]
# test-web-encryption -l
#
# filter is a grep filter to restrict testing to certain
# ssl encryption algorithms.

# OpenSSL requires the port number.
if [[ $# -lt 1 ]]
then
	echo 'Usage: $0 server [port] [grep-filter]'
elif [[ $# -eq 1 && $1 == "-l" ]]
then
	openssl ciphers 'ALL:eNULL' | sed 's/:/\n/g' | sort
	exit
elif [[ $# -ge 2 ]]
then
	SERVER=$1:$2
else
	SERVER=$1:443
fi
if [[ $# -eq 3 ]]
then
	grepcmd="grep -i $3"
else
	grepcmd='cat'
fi

DELAY=1

echo Obtaining cipher list from $(openssl version).

Max=`openssl ciphers 'ALL:eNULL' | sed -e 's/:/\n/g' | $grepcmd | wc -l`
LenMax=${#Max}
((Count=1))
openssl ciphers 'ALL:eNULL' |
	sed -e 's/:/\n/g' |
	$grepcmd |
	while read cipher
	do
	printf "% *d/%d: Testing %-40s " $LenMax $Count $Max $cipher...
	((Count=$Count+1))
	result=$(echo -n | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
	if [[ "$result" =~ "Cipher is (NONE)" ]] ; then
		echo "	NO"
	elif [[ "$result" =~ "Cipher is " ]] ; then
	  echo YES
	else
	  if [[ "$result" =~ ":error:" ]] ; then
	    error=$(echo -n $result | cut -d':' -f6)
	    echo 	NO \($error\)
	  else
	    echo UNKNOWN RESPONSE
	    echo $result
	  fi
	fi
	sleep $DELAY
	done
