#! /usr/bin/perl
#
# Copyright (c) 2005,2009,2011 Martin Consulting Services, Inc.
# Licensed under the Lesser Gnu Public License (LGPL).
# 
# ABSOLUTELY NO WARRENTIES EXPRESSED OR IMPLIED.  ANY USE OF THIS
# CODE IS STRICTLY AT YOUR OWN RISK.
#

#
# Read and filter FreeNAS reports.
#
use strict;
use warnings;
use lib '/usr/local/lib/perl5/site_perl';
use LogOutput;
use ProcessOptions;
use Text::ParseWords;
use FindBin qw($Bin $Script);
use Sys::Hostname;
use POSIX qw(strftime);
use MIME::Base64;

# Initialize variables.
our $Prog=$Script;              	# Get our name, for messages.
$Prog=~s/\.pl$|\.bat$//;            	# Trim off the suffix, if present.
$Prog=~s".*[/\\]"";     	    	# Trim off the path, if present.
our $Errors=0;				# No errors so far.
our $Syslog='USER';			# Name of Syslog facility.  '' for none.
our $BaseDir=$Bin;			# Set our base directory.
our $LogFile="";			# Name of the log file.
our $ConfigFile="$BaseDir";		# Deterimine the name of our config file.
$ConfigFile =~ s"/.[^/]*$"/etc/${Prog}.cfg";# 	Ditto.
our @Parms;				# Array of remaining cmdline parms.
our %Config;				# Our configuration options.
my $ExitCode;				# Code we'll exit with.
#
our $opt_h;				# -h (help) option.
our $opt_e;				# -e (error mail) option.
our $opt_f;				# -e (error mail) option.
our $opt_m;				# -m (mail) option.
our $opt_p;				# -p (pager mail) option.
our $opt_P;				# -P (pager error mail) option.
our $opt_t;				# -t (test) option.
our $opt_v;				# -v (verbose) option.
#

# Note: general purpose script - don't change current directory.
#chdir $BaseDir || die "Unable to change directories to $BaseDir: $!\n";

# Set the ProcessOptions spec here.  This is just like Getopt::Mixed except:
#       1) We define a new type l (lowercase L), which is a list (i.e. if
#          specified multiple times, values are concatenated & blank separated.o
#          Normal =s and =i would replace values instead of concatenate.
#       2) We don't support long option names, except as aliases.
# These are the standard production options.  Add more options here as needed.
my $OptSpec='f=s e=l h m=l O=s p=l P=l t v';

# Load the config file.
if (-e $ConfigFile) {
	open(CONFIG,$ConfigFile) || die("Unable to open $ConfigFile: $!\n");
	# Build a hash of settings found in the config file.
	while (<CONFIG>) {
		next if (/^\s*#/);      # Comment.
		next if (/^\s*$/);      # Blank line.
		chomp;
		my ($name,$settings)=split(/:?\s+/,$_,2);
		$name=~tr/[a-z]/[A-Z]/;
		$Config{$name}.=$settings . ',' ;
	}
	close CONFIG;
	foreach (keys(%Config)) {
		$Config{$_} =~ s/,$//;	# Remove trailing comma
	}
}
foreach (keys(%Config)) { s/,$//;};	# Trim off trailing commas.

# Process the config file defaults if present.
unshift @ARGV, quotewords(" ",0,$Config{'ALLJOBS'})
	if (defined($Config{'ALLJOBS'}));

# Process the command line options, if any.
if (@ARGV) {
	# Process the command line arguments.
	ProcessOptions($OptSpec);
} else {
	# No command line options.  Run the default job.
	ProcessOptions($OptSpec,$Config{'DEFAULTJOB'})
		if (defined($Config{'DEFAULTJOB'}));
}
if ($Errors) {exit $ExitCode;}      # Exit if errors were detected.

# Get the e-mail, so we can retrieve the From and Subject line
my @lines;
if (@Parms) {
	my $FH;
	open($FH,'<',$Parms[0]) || die "Unable to open " . $Parms[0] . ": $!\n";
	@lines = <$FH>;
	close $FH;
}
else {
	print "Reading from STDIN...\n";
	@lines = <STDIN>;
}

my $SendingHost='';
my $From='';
my $Subject='';
foreach (@lines) {
	last if (/^\s*$/);		# Blank line means end of headers.
	$SendingHost = $1 if (/^Received: from (\S+)/i and ! $SendingHost);
	#$From = $_ if (/^From /i and ! $From);
	$Subject = $_ if (/^Subject: /i and ! $Subject);
	last if ($From and $Subject);	# Found all we wanted.
}
$From =~ s/^From\s+//i;		# Strip prefix.
$From =~ s/\s.*$//;		# Strip any trailing data.
$From = getlogin() unless ($From !~ /^\s*$/);
# Subject: SQL Server Job System: 'Test Job' completed on \\ZEUS
my($JobName) = $Subject =~ /.*'(.*?)' completed /;
my($Host) = $Subject =~ /.*' completed on \\\\(\S+)/;
$JobName = "(unknown job)" unless ($JobName);
$Host = $SendingHost unless ($Host);
$Host = "(unknown host)" unless ($Host);
$Host=uc($Host);

# See if we can find a customized filter file.
my $FilterFile='';
foreach my $dir ("/usr/local/etc/$Prog","/usr/local/etc") {
	next unless (-d $dir);
	foreach my $name ("$JobName","$Host.$JobName") {
		if (-r "$dir/$name.filter") {
			$FilterFile="$dir/$name.filter";
			last;
		}
	}
	last if ($FilterFile);
}
	
# Set up our logging and output filtering.
LogOutput({
	ALWAYS_MAIL_LIST =>	$opt_m,
	ALWAYS_PAGE_LIST =>	$opt_p,
	ERROR_MAIL_LIST =>	$opt_e,
	ERROR_PAGE_LIST =>	$opt_P,
	SYSLOG_FACILITY =>	$Syslog,
	MAIL_SUBJECT	=>	"%* %m/%d $Host SQL job $JobName %E %* %* %*",
#	MAIL_FROM	=>	$From,
	CLEAN_UP	=>	\&Cleanup,
	FILTER_FILE	=>	$FilterFile,
	VERBOSE		=>	$opt_v,
});

# Verify the command line.
die("Excess parameters specified on the command line.  See \"$Prog -h\" for usage.")
	if (@Parms > 1);

# Open the copy file if requested.
my $COPYFILE;
if ($opt_f) {
	$opt_f =~ s/%U/$ENV{LOGNAME}/g;
	$opt_f = strftime($opt_f,localtime());
	warn "Unable to open $opt_f: $!" 
		unless open($COPYFILE,'>',$opt_f);
}

my $EndOfHeaders = 0;
my $UULine='';
foreach my $Line (@lines) {
	chomp $Line;
	if ($Line =~ /^[A-Za-z0-9=]+$/) {
		# UU-encoded line.  Collect this for later
		# decoding.
		$UULine .= $Line;
		next;
	}
	else {
		# Standard line.  First, decode any uuencoded text.
		if ($UULine) {
			PrintLine($EndOfHeaders,$COPYFILE,decode_base64($UULine));
			$UULine='';
		}
		# Now, print our current line.
		PrintLine($EndOfHeaders,$COPYFILE,$Line);
		$EndOfHeaders = 1 if ($Line =~ /^\s*$/);
	}
}
warn "No end-of-headers line found\n" unless $EndOfHeaders;
# Print any remaining, unprinted uu-encoded data.
PrintLine($EndOfHeaders,$COPYFILE,decode_base64($UULine))
	if ($UULine);

# Wrap up.
if ($ExitCode) {
	warn "$Prog failed.\n";
} else {
	#print "$Prog ended normally.\n";
}

$ExitCode=$Errors?10:0;
exit($ExitCode);


#
# PrintLine: print out text.
#
sub PrintLine {
	my($EndOfHeaders,$COPYFILE,$Line) = @_;
	print $COPYFILE "$Line\n" if ($COPYFILE);
	print $Line . "\n"
		if ($EndOfHeaders or $Line =~ /^\s*Subject:/i);
}

#
# RunDangerousCmd - run a command, or suppress it if -t specified.
#
sub RunDangerousCmd {
	my ($Cmd,$FH,$Line);
	$Cmd=join(' ',@_);
	if ($opt_t) {
		print "Test: $Cmd\n";
		return 0;
	} else {
		print "Executing: $Cmd\n" if ($opt_v);
		if (open($FH,"$Cmd 2>&1 |")) {
			while ($Line=<$FH>) {
				$Line=~s/[
]//g;
				chomp $Line;
				print "$Line\n";
			};
			close $FH;
			return $?;
		} else {
			warn qq(Unable to start process for "$Cmd": $!\n");
			return 8<<8;
		}
	}
}

sub Cleanup {
	# Force exit code 0, so postfix/alias invocation doesn't think there are problems.
	$LogOutput::ExitCode = 0;
	return 0;
}


#
# opt_h: Usage
#
sub opt_h {

	my $Pagenater=$ENV{PAGENATER};
	$Pagenater="more" unless ($Pagenater);
	system("pod2text $Bin/$Script | $Pagenater");
	exit(1);
}

=pod
=head1 $Prog - >>description<<

=head3 Usage:  
	$Prog [-e mailid] [-m mailid] [-p mailid] [-P mailid] [-O config] [-t|-v] files

	$Prog -h

=head3 Flags:
	-e mailid:      Error: Send an execution report to this e-mail address
			if errors are detected.
        -f copyfile:	File: copy the inbound e-mail to "copyfile".  The argument
			is processed through strftime, allowing standard date/time
			substitutions (e.g. %Y-%m-%d).
	-m mailid:      Mailid: Send an execution report to this e-mail address.
	-p mailid:      Page: Send a very brief message (suitable for a pager)
			to this e-mail address when this job completes.
	-P mailid:      Page error: Send a very brief message to this e-mail 
			address if errors are detected in this job.
	-O config:      Insert the "config" configuration options from
			$ConfigFile.
			the command line at this point.
	-t	:	Test: echo commands instead of running them.
	-v	:	Verbose: echo commands before running them.
	-h      :       Help: display this panel

=head3 Parameters:
	files	:	one or more files to process.

=head3 Return codes:
	0       :       Normal termination
	1       :       Help panel displayed.
	2       :       Invalid or unrecognized command line options.
	3       :       Invalid or unrecognized command line option value.
	4       :       Incorrect command line parameters.
	5       :       Unexpected message found in output.

=cut
__END__
#
# Output filters.  The syntax is: type pattern
#
#  Type:        Ignore - Don't display this message, it's not interesting.
#               LogOnly - Write this message to the syslog and log file, but
#                       don't display it on STDOUT.
#               Show - Display this message, but it's not an error condition.
#               # - This is a comment, ignore it.
#
#  Pattern:     an ordinary perl pattern.  All patterns for a given score
#               are joined by logical OR conditions.
#
#  Notes:
#       1) The "Type" parameter may be specified in upper, lower, or mixed case.
#       2) All messages go to the syslog, regardless of this filter.
#
#
# The following are normal messages we don't need to see.
#
IGNORE  /^\s*$/
#
# These are normal messages that we want to see in the e-mail log only.
#
LOGONLY "^\S+ started on \S+ on \S+, \d+/\d+/\d+ at \d+:\d+:\d+"
LOGONLY /^\s*Command: /
#
# These are normal messages that we want to see.
#
IGNORE  "^\s*\S+ ended normally with status 0 and signal 0$"
SHOW    "^\s*Test:"
SHOW    "^\s*Executing:"
SHOW	"^\s*debug:"
#
# FreeNAS filters
#
SHOW	"^\s*From "
IGNORE	"^\s*$"
IGNORE	"^\s*Return-Path: "
IGNORE	"^\s*X-Original-To: "
IGNORE	"^\s*Delivered-To: "
IGNORE	"^\s*Received: from "
IGNORE	"^\s*by mercury (Postfix) with ESMTP id "
IGNORE	"^\s*for <sqlserver-report\@ "
IGNORE	"^\s*Content-Type: "
IGNORE	"^\s*MIME-Version: "
IGNORE	"^\s*Content-Transfer-Encoding: "
SHOW	"^\s*Subject: SQL Server Job System: '.+' completed on"
IGNORE	"^\s*From: "
IGNORE	"^\s*To: "
IGNORE	"^\s*Date: "
SHOW	"JOB RUN:"
SHOW	"DURATION:"
SHOW	"^\s*STATUS:\s*Succeeded\s*$"
SHOW	"MESSAGES:"
IGNORE	"invoked"
IGNORE	"run was step"
#
# Anything that doesn't match one of these three sets of patterns is considered
# an error.
