#!/usr/bin/perl
#
# =====Description====
#
use LogOutput;
use ProcessOptions;
use Text::ParseWords;
# override CORE::glob in current package
#use File::DosGlob 'glob';    # override CORE::glob in ALL packages (use with extreme caution!)
#use File::DosGlob 'GLOBAL_glob';



# Initialize variables.
$Prog=$0;			# Get our name, for messages.
$Prog=~s/\.pl$|\.bat$//;	# Trim off the suffix, if present.
$Prog=~s".*[/\\]"";		# Trim off the path, if present.
$ENV{PATH} = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
@Args=@ARGV;			# Preserve orig command for ref.
$ErrorFlag=0;			# No errors so far.
$Syslog='user';			# Name of Syslog facility.  '' for none.
$LogFile="";			# Name of the log file.
$ConfigFile="/usr/local/etc/${Prog}.cfg";     # Name of config file.
our @opt_x;
our $opt_D;

my $HostName = `hostname`;
chomp $HostName;
$HostName =~ s/\..*$//;		# Strip domain.
$BaseDir="/usr/local/backup/$HostName";	# Set our base directory.
#

chdir "/usr/local/sbin" || die "Unable to change directories to /usr/local/sbin: $!\n";

# Set the ProcessOptions spec here.  This is just like Getopt::Mixed except:
#       1) We define a new type l (lowercase L), which is a list (i.e. if
#          specified multiple times, values are concatenated & blank separated.o
#          Normal =s and =i would replace values instead of concatenate.
#       2) We don't support long option names, except as aliases.
# These are the standard production options.  Add more options here as needed.
$OptSpec='D=s h t m=l e=l O=s p=l P=l x=l t v';

# ---------------------------------------------------------
#
# Load the config file.
#
if (-e $ConfigFile) {
	open(CONFIG,$ConfigFile) || die("Unable to open $ConfigFile: $!\n");
	# Build a hash of settings found in the config file.
	while (<CONFIG>) {
		next if (/^\s*#/);      # Comment.
		next if (/^\s*$/);      # Blank line.
		chomp;
		($name,$settings)=split(/:?\s+/,$_,2);
		$name=~tr/[a-z]/[A-Z]/;
		$Config{$name}.=$settings . ',' ;
	}
	close CONFIG;
	foreach (keys(%Config)) {
		$Config{$_} =~ s/,$//;	# Remove trailing comma
	}
}
foreach (keys(%Config)) { s/,$//;};	# Trim off trailing commas.

# ---------------------------------------------------------
#
# Process the config file defaults if present.
#
unshift @ARGV, quotewords(" ",0,$Config{'ALLJOBS'})
	if (defined($Config{'ALLJOBS'}));

# Process the command line options, if any.
if (@ARGV) {
	# Process the command line arguments.
	ProcessOptions($OptSpec);
} else {
	# No command line options.  Run the default job.
	ProcessOptions($OptSpec,$Config{'DEFAULTJOB'})
		if (defined($Config{'DEFAULTJOB'}));
}
if ($ErrorFlag) {exit $ErrorFlag;}      # Exit if errors were detected.
	
# Set up our logging and output filtering.
LogOutput('',$Syslog,$LogFile,$opt_m,$opt_e,$opt_p,$opt_P);

# Verify the command line.
die("Excess parameters on the command line.  See \"$Prog -h\" for usage.")
	if ($Parms);

# ---------------------------------------------------------
#
# Identify the output directory and create it if necessary.
#
my $OutputDir;
if ($opt_D) {
	$OutputDir = $opt_D;
}
else {
	$OutputDir=`date +$BaseDir/%m-%d`;
}
chomp $OutputDir;

RunDangerousCmd("mkdir -p --mode=750 $OutputDir") unless (-e $OutputDir);
RunDangerousCmd("chgrp sys $OutputDir") &&
	die "Unable to set group for $OutputDir: $!\n";
chdir $OutputDir || die "Unable to change directories to $OutputDir: $!\n";


# ---------------------------------------------------------
#
# Keep the most recent five back-ups.
#
if (open($FHLS,"ls -dt $BaseDir/[01][0-9]-[0-3][0-9] |")) {
        my $Count=0;
	while (<$FHLS>) {
		$Count++;
                RunDangerousCmd("rm -rf $_") if ($Count > 5);
	}
	close $FHLS;
} else {
	warn "Unable to open ls command: $!\n";
}

# ---------------------------------------------------------
#
# Use the mount command to determine what to back up.
#
if (open($FHMOUNT,'mount |')) {
	MOUNT: while (<$FHMOUNT>) {
		chomp;

		# Skip transient file systems based on type.
		next if (/type (sysfs|proc|tmpfs|devpts|subfs|usbfs|sysfs|debugfs|securityfs)/);

		# Skip anything under /mnt as being temporary.
		next if (m"^\S+ on /mnt/");

		# Skip our own output area.
		next if (m"^\S+ on $BaseDir");
		
		# Get the mount point, and compare to our exclude list.
		my $MountPt;
		($MountPt)=(split(/\s+/))[2];
		foreach $ExcludedMount (@opt_x) {
			next MOUNT if ($MountPt =~ m"^$ExcludedMount(/.*)?$");
		}

		# Build the output file name.
		my $OutputFile;
		my $OutputName;
                ($OutputName="$MountPt") =~ s"^.*/"";
                $OutputName="root" if ($OutputName eq '');
                $OutputFile="$OutputName.tgz";

		# Do it.
		my $ExcludeFile = "$BaseDir/$OutputName.exclude";
		if (-f $ExcludeFile) {
			$ExcludeFile = "-X $ExcludeFile";
		} else {
			$ExcludeFile = "";
		}
			
                RunDangerousCmd("tar -cz --one-file-system " .
			"-f $OutputDir/$OutputFile " .
			"-C $MountPt " .
                        "$ExcludeFile ."
                        );
	}
} else {
	die "Unable to issue mount command: $!\n";
}

# ---------------------------------------------------------
#
# Capture recovery information here, also.
#
RunDangerousCmd("recovery-info -o $OutputDir/recovery");

if ($ExitCode) {
	warn "$Prog failed.\n";
} else {
	#print "$Prog ended normally.\n";
}

$ExitCode=$Errors?10:0;
exit($ExitCode);

# ---------------------------------------------------------
#
# RunDangerousCmd - run a command, or suppress it if -t specified.
#
sub RunDangerousCmd {
	my ($Cmd,$FH,$Line);
	$Cmd=join(' ',@_);
	if ($opt_t) {
		print "Test: $Cmd\n";
		return 0;
	} else {
		print "Executing: $Cmd\n" if ($opt_v);
		if (open($FH,"$Cmd 2>&1 |")) {
			while ($Line=<$FH>) {
				$Line=~s/[
]//g;
				chomp $Line;
				print "$Line\n";
			};
			close $FH;
			return $?;
		} else {
			warn qq(Unable to start process for "$Cmd": $!\n");
			return 8<<8;
		}
	}
}


# ---------------------------------------------------------
#
# opt_h: Usage
#
sub opt_h {

	open (PAGENATER,"| more") || die("Unable to start pagenater: $!\n");
	print PAGENATER <<"ENDUSAGE";
$Prog - Zip selected shared folders onto the snap server.

Usage:  $Prog [-e mailid] [-m mailid] [-p mailid] [-P mailid] [-O config] [-t|-v] files
	$Prog -h

Flags:
	-e mailid:      Error: Send an execution report to this e-mail address
			if errors are detected.
	-m mailid:      Mailid: Send an execution report to this e-mail address.
	-p mailid:      Page: Send a very brief message (suitable for a pager)
			to this e-mail address when this job completes.
	-P mailid:      Page error: Send a very brief message to this e-mail 
			address if errors are detected in this job.
	-O config:      Insert the "config" configuration options from
			$ConfigFile.
			the command line at this point.
	-t	:	Test: echo commands instead of running them.
	-v	:	Verbose: echo commands before running them.
	-h      :       Help: display this panel

Parameters:
	files	:	one or more files to zip.

Return codes:
	0       :       Normal termination
	1       :       Help panel displayed.
	2       :       Invalid or unrecognized command line options.
	3       :       Invalid or unrecognized command line option value.
	4       :       Incorrect command line parameters.
	5       :       Unexpected message found in output.
	10      :       Some delete's failed.
ENDUSAGE
close PAGENATER;
exit 1;
}
__END__
#
# ---------------------------------------------------------
#
# Output filters.  The syntax is: type pattern
#
#  Type:        Ignore - Don't display this message, it's not interesting.
#               LogOnly - Write this message to the syslog and log file, but
#                       don't display it on STDOUT.
#               Show - Display this message, but it's not an error condition.
#               # - This is a comment, ignore it.
#
#  Pattern:     an ordinary perl pattern.  All patterns for a given score
#               are joined by logical OR conditions.
#
#  Notes:
#       1) The "Type" parameter may be specified in upper, lower, or mixed case.
#       2) All messages go to the syslog, regardless of this filter.
#
#
# The following are normal messages we don't need to see.
#
IGNORE	/^tar: .* socket ignored$/
IGNORE	"^tar: Removing leading `/' from member names$"
IGNORE	"^tar: /var/lib/mysql/maia/maia_mail.MYD: file changed as we read it$"
IGNORE	"^tar: Error exit delayed from previous errors$"
IGNORE	"^\s*512 bytes \(512 B\) copied, \d+.\d+ seconds, \d+\.\d+ [kmgKMG]B$"
IGNORE	"^\s*512 bytes \(512 B\) copied, \d+.\d+(e-\d+)? s, \d+\.\d+ [kmgKMG]B/s"
IGNORE	"^\s*recovery-info started on \S+ on"
IGNORE  /^\s*$/
#
# These are normal messages that we want to see in the e-mail log only.
#
LOGONLY "^\S+ started on \S+ on \d+/\d+/\d+"
LOGONLY /^Command: /
#
# These are normal messages that we want to see.
#
SHOW    /^Job ended normally with status 0 and signal 0$/
SHOW    /^Test:/
SHOW    /^Executing:/
SHOW	/^\s*debug:/
#
# Anything that doesn't match one of these three sets of patterns is considered
# an error.
